### ISSUE TITLE
Player.Ship is not set if you are player 2

### ISSUE THREAD

**Issue by EntelectChallenge** [EntelectChallenge/2015-SpaceInvaders-TestHarness#1]
Logged on behalf of GroenBoer from the Challenge forums:

I have played around with the test harness and demo bot. Everything from the initial setup works fine up until I customize the code a bit and load it in as Player 2 in the test harness (the precompiled version). In this case the Player 2 instance never seems to populate the Ships property for either.
Both of these lines of code return null when in execute it as player two
currentMatch.Players[0].Ship
currentMatch.Players[1].Ship

Is anyone else having the same problem?

**Comment by mattpwest** [comment]
I forgot to copy and flip the ship when doing so for the Player...

Fixed by: ce691f0bf12737e3826832de4b6e876921bbdba8

**Comment by leppie** [comment]
Same with lost MissileController. See https://github.com/EntelectChallenge/2015-SpaceInvaders-TestHarness/issues/7
