### ISSUE TITLE
"The handle is invalid" error when called from external app

### ISSUE THREAD

**Issue by demaniak** [EntelectChallenge/2015-SpaceInvaders-TestHarness#13]
[This SO link seems to hit the nail on the head](http://stackoverflow.com/questions/327408/the-handle-is-invalid-when-running-net-console-via-java).

Basically when calling the test harness from external application (yes...I am...doing...things...to it), that error occurs (stack trace follows below). I suspect the solution is as simple as wrapping the console cursor manipulation calls in try-catch blocks.

<pre>
Something went wrong...
The handle is invalid.

    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
    at System.Console.Clear()
    at ChallengeHarness.Loggers.ConsoleLogger..ctor() in c:\Dev\100K\2015-SpaceInvaders-TestHarness\ChallengeHarness\Loggers\ConsoleLogger.cs:line 13
    at ChallengeHarness.Runners.MatchRunner..ctor(IMatch match, String playerOneFolder, String playerTwoFolder, IRenderer renderer) in c:\Dev\100K\2015-SpaceInvaders-TestHarness\ChallengeHarness\Runners\MatchRunner.cs:line 21
    at SpaceInvadersDuel.Program.Main(String[] args) in c:\Dev\100K\2015-SpaceInvaders-TestHarness\SpaceInvadersDuel\Program.cs:line 38
</pre>

**Comment by demaniak** [comment]
Ok, had a look at the ConsoleLogger code now, and maybe **not** exactly as easy as wrapping problematic calls in try-catch.

If the `Console.clear()` call is handled, the next problem will be in `WriteToConsoleAndDebug(...)` with the usage of `Console.SetCursorPosition`

**Comment by mattpwest** [comment]
Have a look at: https://github.com/EntelectChallenge/2015-SpaceInvaders-TestHarness/blob/master/ChallengeHarness/Loggers/ConsoleLogger.cs#L19...

The best solution may be to separate the scrolling and setCursor loggers into separate classes and move that automatic selection of a strategy up to MatchRunner. Then add another command line argument that you can use to force it to use the scrolling mode when you want to... do things to it?

**Comment by demaniak** [comment]
hehehe, yeah, working on something like that now.

Thanks Matt.

PS: feel free to close the issue if nobody else is hitting this sorta problem.

**Comment by mattpwest** [comment]
I'll keep it open...

The player dashboard where players can upload their bot will run a test match against a reference bot and the tournament management software also probably just forks the test harness after copying in bots. So we probably need to fix this soon anyway.

**Comment by mattpwest** [comment]
@demaniak Just released [v1.0.2](https://github.com/EntelectChallenge/2015-SpaceInvaders-TestHarness/releases) which adds -s | --scrolling to force scrolling console logging and -q | --quiet to disable console logging entirely.
