### ISSUE TITLE
Number of lives is inconsistent between building and dying

### ISSUE THREAD

**Issue by mattpwest** [EntelectChallenge/2015-SpaceInvaders-TestHarness#2]
Reported on behalf of MajorPAIN from the challenge forums.

I have noticed that you are able to build 3 buildings, and then when your ship dies you lose.
You also lose when you build 2 buildings and your ship dies.
And then you also lose when your ship dies 3 times.
Should you be able to build 3 buildings? Seems like the limit should be 2.

**Comment by mattpwest** [comment]
Moved life deduction from dying to spawning and fixed win conditions accordingly. Players will now start with 1 ship and 3 lives in the bank so the actual total is 4 lives.

See f8f6649379eeafdd8301c96352ab9a146ff5ad42.

**Comment by mattpwest** [comment]
Actually that's incorrect... your initial spawn will use up 1 life: so you start with 3 before you see the initial game state and spawn for the first time.

Then you have 2 lives left, so you have a total of 3.

I'll clarify on Monday whether we should give you 1 ship and 3 lives for a total of 4 OR 1 ship and 2 lives for a total of 3... as soon as I have call on this from management I'll make a new binary release with all the fixes.

**Comment by Tjorriemorrie** [comment]
I vote for total of 4. It allows more strategy to use buildings.

**Comment by mattpwest** [comment]
Management agrees :)
