### ISSUE TITLE
Off-by-one in Alien collisions

### ISSUE THREAD

**Issue by cynic** [EntelectChallenge/2015-SpaceInvaders-TestHarness#26]
To reproduce: Create Bot X which issues 5 Nothing commands, followed by a Shoot command.  Create Bot Y which issues 6 Nothing commands, followed by a Shoot command.

Expected: Bot X's shot should hit an Alien.  Bot Y's shot should narrowly miss the same Alien.

Actual: Both Bot X and Bot Y's shots will hit the Alien.

**Comment by Pyroseza** [comment]
I don't think this is an issue, I've noticed it earlier that all the bullets & missiles work this way. If you have a bullet right in front of your ship like literally the very next space above your ship either on the left side or right side you can not dodge it and it will hit your ship, it is the order in which the test harness executes it's checks.

**Comment by cynic** [comment]
Yes, I figured out that it is because the collision checks are executed incorrectly.  Entity creation should happen, then movable object should move _before_ collision-checks are performed, and then collision checks should be performed.  (Given the size of the problem domain, I'd have used a 2D array for making the checks quick'n'easy without having to rely upon object specialization (which distributes similar logic across a lot of code) ... but that's neither here nor there ;)) And it's good to get confirmation that this affects ship collisions as well.

There are two consequences of this. The first is that it is impossible to time missiles to "just miss" an Alien (or Ship) by going "behind" it.  I think this reduces the strategic depth a bit.  The second is that every moving object drags a "virtual" and invisible copy of itself behind itself.  I don't know how a GUI is going to represent this (maybe by a "shadow"?), but if it isn't represented, then it leads to near-misses that destroy the object, and that is just weird to see.

If this is intended behaviour then it should be confirmed to be working as expected, and possibly codified in the rules somewhere (it is unusual behaviour!), and developers can then make the necessary assumptions for their bots.

**Comment by Pyroseza** [comment]
Here you go from the Rules page on the the challenge website:

Advance the game state by 1 round:

```
Update the alien commander to spawn new aliens and give aliens orders;
Update missiles, moving them forward;
Update alien bullets, moving them forward;
Update aliens, executing their move & shoot orders;
Update ships, executing their orders;
Advance respawn timer and respawn ships if necessary.
```

**Comment by cynic** [comment]
The issue is when collision checks occur, and this is not referred to.  If they occur after missiles&bullets move, then Bot X's shot should miss, and Bot Y's shot should hit.  If they occur after all updates, then Bot X's shot should hit, and Bot Y's shot should miss.  But if _both_ shots hit, then that means that the Alien is actually in two places at one time.

But maybe I'm missing your point ... are you officially confirming that the behaviour is correct, and bots should be coded for this behaviour?

**Comment by amanica** [comment]
In another thread it was confirmed that collition checks happen during each
step.
I picture it as the missile hitting the allien or the allien hitting the
missile ..

**Comment by Pyroseza** [comment]
Let's see what Matt says about this, I see it as a "feature" and not a bug, but I guess if it is inconsistent on both sides then yeah it is a bug, have you by any chance read through the harness' code? Perhaps you can find where it is going wrong.

**Comment by mattpwest** [comment]
Maybe it's just because I wrote it, but this was by design and it makes sense to me. Missiles move, then aliens, then ships and collisions are resolved whenever something moves. So for player 1 the alien is moving into the missile next to it, while for player 2 the missile is hitting the alien head on.

Also note that we're 2 months into the challenge now and changing this will affect game balance and likely break bots that are already working are dependent on how it works... So I'd rather not make such a major change now.

**Comment by cynic** [comment]
Thanks, just wanted official confirmation that this is expected behaviour.  I'll code for this.
