### ISSUE TITLE
BotRunner.CreateProcess repeatedly prepends /bin/bash to the process name

### ISSUE THREAD

**Issue by mattpwest** [EntelectChallenge/2015-SpaceInvaders-TestHarness#3]
Need to change the code to perform process renaming when running on Linux once-off on creation of the BotRunner instead of with every call to BotRunner.CreateProcess().

**Comment by pierre-pretorius** [comment]
I get the same issue, more detail here: http://forum.entelect.co.za/thread/error-when-running-test-harness-on-linux/

**Comment by pierre-pretorius** [comment]
I can confirm it's fixed in 1.0.1.
